;;; ivory-themes.el --- Minimal monochromatic themes -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Kaung Htet

;; Author: Kaung Htet
;; Maintainer: Kaung Htet
;; URL: https://github.com/khzaw/ivory-themes
;; Version: 0.1.0
;; Package-Requires: ((emacs "28.1"))
;; Keywords: faces, theme

;;; Commentary:

;; Ivory is a pair of minimal monochromatic themes.  The light and dark
;; variants share one semantic palette and face generator, keeping the theme
;; easy to tune while still covering common built-in and third-party faces.

;;; Code:

(eval-when-compile
  (require 'subr-x))

(defgroup ivory-themes nil
  "User options for the Ivory themes."
  :group 'faces
  :prefix "ivory-themes-"
  :tag "Ivory Themes")

(defcustom ivory-themes-bold-constructs t
  "When non-nil, use bold weight to create syntax and UI contrast."
  :type 'boolean
  :group 'ivory-themes)

(defcustom ivory-themes-italic-constructs nil
  "When non-nil, allow italic text in faces that conventionally use it."
  :type 'boolean
  :group 'ivory-themes)

(defcustom ivory-themes-common-palette-overrides nil
  "Palette overrides shared by all Ivory themes.

Each entry has the form (NAME . HEX-COLOR).  The palette names are the
keys in `ivory-themes-palettes'.  Set this before loading or reloading an
Ivory theme."
  :type '(alist :key-type symbol :value-type string)
  :group 'ivory-themes)

(defcustom ivory-themes-light-palette-overrides nil
  "Palette overrides for `ivory-light'.

This uses the same format as `ivory-themes-common-palette-overrides'."
  :type '(alist :key-type symbol :value-type string)
  :group 'ivory-themes)

(defcustom ivory-themes-dark-palette-overrides nil
  "Palette overrides for `ivory-dark'.

This uses the same format as `ivory-themes-common-palette-overrides'."
  :type '(alist :key-type symbol :value-type string)
  :group 'ivory-themes)

(defconst ivory-themes-palettes
  '((light
     . ((bg . "#ffffff")
        (bg-alt . "#f7f7f7")
        (bg-dim . "#f0f0f0")
        (bg-active . "#e6e6e6")
        (bg-subtle . "#fbfbfb")
        (bg-block . "#f3f3f3")
        (bg-hl . "#eeeeee")
        (bg-region . "#d8d8d8")
        (bg-search . "#d0d0d0")
        (bg-modeline . "#e2e2e2")
        (bg-modeline-inactive . "#fafafa")
        (modeline-accent . "#8a8a8a")
        (fg . "#111111")
        (fg-alt . "#404040")
        (fg-dim . "#858585")
        (fg-faint . "#b8b8b8")
        (fg-name . "#404040")
        (fg-syntax . "#111111")
        (fg-comment . "#999999")
        (fg-comment-delimiter . "#c4c4c4")
        (fg-inactive . "#8a8a8a")
        (border . "#dcdcdc")
        (cursor . "#000000")
        (red . "#8f1313")
        (red-faint . "#b54545")
        (green . "#005000")
        (green-faint . "#287a37")
        (yellow . "#6f5700")
        (blue . "#333333")
        (bg-added . "#c1f2d1")
        (bg-added-faint . "#d8f8e1")
        (bg-removed . "#ffd8d5")
        (bg-removed-faint . "#ffe9e9")
        (bg-changed . "#f5edcf")
        (bg-changed-faint . "#faf5df")
        (fg-added . "#005000")
        (fg-added-intense . "#006700")
        (fg-removed . "#8f1313")
        (fg-removed-intense . "#aa2222")
        (fg-changed . "#6f5700")
        (fg-changed-intense . "#806400")))
    (dark
     . ((bg . "#000000")
        (bg-alt . "#060606")
        (bg-dim . "#111111")
        (bg-active . "#2d2d2d")
        (bg-subtle . "#050505")
        (bg-block . "#121212")
        (bg-hl . "#1a1a1a")
        (bg-region . "#3a3a3a")
        (bg-search . "#4a4a4a")
        (bg-modeline . "#303030")
        (bg-modeline-inactive . "#070707")
        (modeline-accent . "#b0b0b0")
        (fg . "#eeeeee")
        (fg-alt . "#c2c2c2")
        (fg-dim . "#595959")
        (fg-faint . "#2b2b2b")
        (fg-name . "#9c9c9c")
        (fg-syntax . "#9c9c9c")
        (fg-comment . "#595959")
        (fg-comment-delimiter . "#2b2b2b")
        (fg-inactive . "#777777")
        (border . "#282828")
        (cursor . "#f2f2f2")
        (red . "#ff5f5f")
        (red-faint . "#ff8c8c")
        (green . "#8bd48b")
        (green-faint . "#66aa66")
        (yellow . "#e0c45a")
        (blue . "#d8d8d8")
        (bg-added . "#00381f")
        (bg-added-faint . "#002910")
        (bg-removed . "#4f1119")
        (bg-removed-faint . "#380a0f")
        (bg-changed . "#373012")
        (bg-changed-faint . "#24200c")
        (fg-added . "#a0e0a0")
        (fg-added-intense . "#80e080")
        (fg-removed . "#ff9c9c")
        (fg-removed-intense . "#ff6f75")
        (fg-changed . "#e0d090")
        (fg-changed-intense . "#f0da80"))))
  "Base palettes for the Ivory themes.")

(eval-and-compile
  (defconst ivory-themes--color-names
    '(bg bg-alt bg-dim bg-active bg-subtle bg-block bg-hl bg-region bg-search
         bg-modeline bg-modeline-inactive modeline-accent
         fg fg-alt fg-dim fg-faint fg-name fg-syntax fg-comment fg-comment-delimiter
         fg-inactive border cursor
         red red-faint green green-faint yellow blue bg-added
         bg-added-faint bg-removed bg-removed-faint bg-changed bg-changed-faint
         fg-added fg-added-intense fg-removed fg-removed-intense fg-changed
         fg-changed-intense)))

(defun ivory-themes--alist-get (key alist)
  "Return KEY from ALIST, or signal a user-facing error."
  (or (alist-get key alist)
      (user-error "Ivory theme palette is missing `%s'" key)))

(defun ivory-themes--palette (variant)
  "Return the merged palette for VARIANT."
  (let* ((base (or (alist-get variant ivory-themes-palettes)
                   (user-error "Unknown Ivory theme variant `%s'" variant)))
         (variant-overrides
          (pcase variant
            ('light ivory-themes-light-palette-overrides)
            ('dark ivory-themes-dark-palette-overrides)
            (_ nil))))
    (append variant-overrides ivory-themes-common-palette-overrides base)))

(defmacro ivory-themes--with-colors (palette &rest body)
  "Bind colors from PALETTE around BODY."
  (declare (indent 1))
  `(let ,(mapcar (lambda (name)
                   `(,name (ivory-themes--alist-get ',name ,palette)))
                 ivory-themes--color-names)
     (ignore ,@ivory-themes--color-names)
     ,@body))

(defun ivory-themes--face (face spec)
  "Return a `custom-theme-set-faces' entry for FACE using SPEC."
  (list face `((t ,spec))))

(defun ivory-themes--faces-basic (palette)
  "Return basic editor and UI faces for PALETTE."
  (ivory-themes--with-colors palette
    (let ((slant (if ivory-themes-italic-constructs 'italic 'normal)))
      (list
       (ivory-themes--face 'default `(:background ,bg :foreground ,fg))
       (ivory-themes--face 'cursor `(:background ,cursor))
       (ivory-themes--face 'fringe `(:background ,bg :foreground ,fg-faint))
       (ivory-themes--face 'highlight `(:background ,bg-hl :foreground ,fg))
       (ivory-themes--face 'hl-line `(:background ,bg-subtle :extend t))
       (ivory-themes--face 'region `(:background ,bg-region :foreground ,fg :extend t))
       (ivory-themes--face 'secondary-selection `(:background ,bg-active :foreground ,fg :extend t))
       (ivory-themes--face 'isearch `(:background ,bg-search :foreground ,fg :weight bold))
       (ivory-themes--face 'isearch-fail `(:background ,bg-removed :foreground ,fg-removed :weight bold))
       (ivory-themes--face 'lazy-highlight `(:background ,bg-active :foreground ,fg))
       (ivory-themes--face 'match `(:background ,bg-active :foreground ,fg :weight bold))
       (ivory-themes--face 'trailing-whitespace `(:background ,bg-removed))
       (ivory-themes--face 'shadow `(:foreground ,fg-dim))
       (ivory-themes--face 'bold `(:weight bold))
       (ivory-themes--face 'italic `(:slant ,slant))
       (ivory-themes--face 'bold-italic `(:weight bold :slant ,slant))
       (ivory-themes--face 'fixed-pitch `(:family "Monospace"))
       (ivory-themes--face 'variable-pitch `(:family "Sans Serif"))
       (ivory-themes--face 'escape-glyph `(:foreground ,fg-alt :weight bold))
       (ivory-themes--face 'homoglyph `(:foreground ,fg-alt :weight bold))
       (ivory-themes--face 'link `(:foreground ,fg :underline t))
       (ivory-themes--face 'link-visited `(:foreground ,fg-dim :underline t))
       (ivory-themes--face 'button `(:foreground ,fg :underline t))
       (ivory-themes--face 'success `(:foreground ,green :weight bold))
       (ivory-themes--face 'warning `(:foreground ,yellow :weight bold))
       (ivory-themes--face 'error `(:foreground ,red :weight bold))
       (ivory-themes--face 'vertical-border `(:foreground ,border))
       (ivory-themes--face 'window-divider `(:foreground ,border))
       (ivory-themes--face 'window-divider-first-pixel `(:foreground ,border))
       (ivory-themes--face 'window-divider-last-pixel `(:foreground ,border))
       (ivory-themes--face 'show-paren-match `(:background ,bg-active :foreground ,fg :weight bold))
       (ivory-themes--face 'show-paren-mismatch `(:background ,bg-removed :foreground ,fg-removed :weight bold))
       (ivory-themes--face 'line-number `(:background ,bg :foreground ,fg-faint))
       (ivory-themes--face 'line-number-current-line `(:background ,bg :foreground ,fg :weight bold))
       (ivory-themes--face 'linum `(:inherit line-number))
       (ivory-themes--face 'fill-column-indicator `(:foreground ,border))
       (ivory-themes--face 'display-fill-column-indicator `(:foreground ,border))
       (ivory-themes--face 'whitespace-space `(:foreground ,fg-faint))
       (ivory-themes--face 'whitespace-tab `(:foreground ,fg-faint))
       (ivory-themes--face 'whitespace-newline `(:foreground ,fg-faint))
       (ivory-themes--face 'whitespace-trailing `(:background ,bg-removed :foreground ,fg-removed))
       (ivory-themes--face 'whitespace-line `(:background ,bg-changed-faint :foreground ,fg-changed))
       (ivory-themes--face 'header-line `(:background ,bg-alt :foreground ,fg-alt :box (:line-width -1 :color ,border)))
       (ivory-themes--face 'header-line-highlight `(:background ,bg-active :foreground ,fg :weight bold))
       (ivory-themes--face 'mode-line `(:background ,bg-modeline :foreground ,fg :box (:line-width 1 :color ,modeline-accent)))
       (ivory-themes--face 'mode-line-active `(:inherit mode-line :background ,bg-modeline :foreground ,fg :box (:line-width 1 :color ,modeline-accent)))
       (ivory-themes--face 'mode-line-inactive `(:background ,bg-modeline-inactive :foreground ,fg-inactive :box (:line-width -1 :color ,border)))
       (ivory-themes--face 'mode-line-buffer-id `(:weight bold))
       (ivory-themes--face 'mode-line-emphasis `(:weight bold))
       (ivory-themes--face 'mode-line-highlight `(:background ,bg-active :foreground ,fg :weight bold))
       (ivory-themes--face 'minibuffer-prompt `(:foreground ,fg :weight bold))
       (ivory-themes--face 'tooltip `(:background ,bg-alt :foreground ,fg :box (:line-width -1 :color ,border)))
       (ivory-themes--face 'child-frame-border `(:background ,border))
       (ivory-themes--face 'tab-bar `(:background ,bg-alt :foreground ,fg-dim))
       (ivory-themes--face 'tab-bar-tab `(:background ,bg :foreground ,fg :weight bold :box (:line-width -1 :color ,border)))
       (ivory-themes--face 'tab-bar-tab-inactive `(:background ,bg-alt :foreground ,fg-dim :box (:line-width -1 :color ,border)))
       (ivory-themes--face 'tab-line `(:background ,bg-alt :foreground ,fg-dim))
       (ivory-themes--face 'tab-line-tab `(:background ,bg :foreground ,fg :box (:line-width -1 :color ,border)))
       (ivory-themes--face 'tab-line-tab-current `(:background ,bg :foreground ,fg :weight bold :box (:line-width -1 :color ,border)))
       (ivory-themes--face 'tab-line-tab-inactive `(:background ,bg-alt :foreground ,fg-dim :box (:line-width -1 :color ,border)))))))

(defun ivory-themes--faces-font-lock (palette)
  "Return font-lock and Tree-sitter faces for PALETTE."
  (ivory-themes--with-colors palette
    (let ((bold (if ivory-themes-bold-constructs 'bold 'normal)))
      (list
       (ivory-themes--face 'font-lock-builtin-face `(:foreground ,fg-syntax))
       (ivory-themes--face 'font-lock-comment-face `(:foreground ,fg-comment))
       (ivory-themes--face 'font-lock-comment-delimiter-face `(:foreground ,fg-comment-delimiter))
       (ivory-themes--face 'font-lock-constant-face `(:foreground ,fg-alt :weight ,bold))
       (ivory-themes--face 'font-lock-doc-face `(:foreground ,fg-comment))
       (ivory-themes--face 'font-lock-doc-markup-face `(:foreground ,fg-alt :weight ,bold))
       (ivory-themes--face 'font-lock-function-name-face `(:foreground ,fg :weight ,bold))
       (ivory-themes--face 'font-lock-keyword-face `(:foreground ,fg-syntax :weight ,bold))
       (ivory-themes--face 'font-lock-negation-char-face `(:foreground ,fg-syntax))
       (ivory-themes--face 'font-lock-number-face `(:foreground ,fg-alt))
       (ivory-themes--face 'font-lock-operator-face `(:foreground ,fg-syntax))
       (ivory-themes--face 'font-lock-preprocessor-face `(:foreground ,fg-syntax))
       (ivory-themes--face 'font-lock-property-name-face `(:foreground ,fg-name :weight normal))
       (ivory-themes--face 'font-lock-property-use-face `(:foreground ,fg-name))
       (ivory-themes--face 'font-lock-punctuation-face `(:foreground ,fg-alt))
       (ivory-themes--face 'font-lock-regexp-face `(:foreground ,fg-alt :weight ,bold))
       (ivory-themes--face 'font-lock-regexp-grouping-backslash `(:foreground ,fg :weight ,bold))
       (ivory-themes--face 'font-lock-regexp-grouping-construct `(:foreground ,fg :weight ,bold))
       (ivory-themes--face 'font-lock-string-face `(:foreground ,fg-alt))
       (ivory-themes--face 'font-lock-type-face `(:foreground ,fg :weight ,bold))
       (ivory-themes--face 'font-lock-variable-name-face `(:foreground ,fg-name))
       (ivory-themes--face 'font-lock-variable-use-face `(:foreground ,fg-name))
       (ivory-themes--face 'font-lock-warning-face `(:inherit warning))
       (ivory-themes--face 'tree-sitter-hl-face:attribute `(:inherit font-lock-property-name-face))
       (ivory-themes--face 'tree-sitter-hl-face:constant `(:inherit font-lock-constant-face))
       (ivory-themes--face 'tree-sitter-hl-face:comment `(:inherit font-lock-comment-face))
       (ivory-themes--face 'tree-sitter-hl-face:function `(:inherit font-lock-function-name-face))
       (ivory-themes--face 'tree-sitter-hl-face:function.call `(:foreground ,fg))
       (ivory-themes--face 'tree-sitter-hl-face:keyword `(:inherit font-lock-keyword-face))
       (ivory-themes--face 'tree-sitter-hl-face:method `(:inherit font-lock-function-name-face))
       (ivory-themes--face 'tree-sitter-hl-face:operator `(:inherit font-lock-operator-face))
       (ivory-themes--face 'tree-sitter-hl-face:property `(:inherit font-lock-property-name-face))
       (ivory-themes--face 'tree-sitter-hl-face:string `(:inherit font-lock-string-face))
       (ivory-themes--face 'tree-sitter-hl-face:type `(:inherit font-lock-type-face))
       (ivory-themes--face 'tree-sitter-hl-face:variable `(:inherit font-lock-variable-name-face))))))

(defun ivory-themes--faces-outline (palette)
  "Return outline and heading faces for PALETTE."
  (ivory-themes--with-colors palette
    (let ((bold (if ivory-themes-bold-constructs 'bold 'normal)))
      (list
       (ivory-themes--face 'outline-1 `(:foreground ,fg :weight bold :height 1.20))
       (ivory-themes--face 'outline-2 `(:foreground ,fg :weight bold :height 1.12))
       (ivory-themes--face 'outline-3 `(:foreground ,fg-alt :weight bold :height 1.06))
       (ivory-themes--face 'outline-4 `(:foreground ,fg-alt :weight ,bold))
       (ivory-themes--face 'outline-5 `(:foreground ,fg-alt :weight ,bold))
       (ivory-themes--face 'outline-6 `(:foreground ,fg-dim :weight ,bold))
       (ivory-themes--face 'outline-7 `(:foreground ,fg-dim :weight ,bold))
       (ivory-themes--face 'outline-8 `(:foreground ,fg-dim :weight ,bold))))))

(defun ivory-themes--faces-completion (palette)
  "Return completion, narrowing, and minibuffer package faces for PALETTE."
  (ivory-themes--with-colors palette
    (let ((match `(:foreground ,fg :weight bold))
          (selected `(:background ,bg-active :foreground ,fg :weight bold)))
      (append
       (list
        (ivory-themes--face 'completions-annotations `(:foreground ,fg-dim))
        (ivory-themes--face 'completions-common-part match)
        (ivory-themes--face 'completions-first-difference `(:foreground ,fg :weight bold))
        (ivory-themes--face 'completions-highlight selected)
        (ivory-themes--face 'orderless-match-face-0 match)
        (ivory-themes--face 'orderless-match-face-1 match)
        (ivory-themes--face 'orderless-match-face-2 match)
        (ivory-themes--face 'orderless-match-face-3 match)
        (ivory-themes--face 'consult-highlight-match match)
        (ivory-themes--face 'consult-preview-match `(:background ,bg-search :foreground ,fg :weight bold))
        (ivory-themes--face 'consult-file `(:foreground ,fg))
        (ivory-themes--face 'consult-line-number-prefix `(:foreground ,fg-faint))
        (ivory-themes--face 'consult-line-number-wrapped `(:foreground ,fg-faint))
        (ivory-themes--face 'vertico-current selected)
        (ivory-themes--face 'vertico-group-title `(:foreground ,fg-dim :weight bold))
        (ivory-themes--face 'vertico-group-separator `(:foreground ,border))
        (ivory-themes--face 'marginalia-documentation `(:foreground ,fg-dim))
        (ivory-themes--face 'marginalia-key `(:foreground ,fg :weight bold))
        (ivory-themes--face 'marginalia-modified `(:foreground ,yellow :weight bold))
        (ivory-themes--face 'marginalia-null `(:foreground ,fg-faint))
        (ivory-themes--face 'marginalia-size `(:foreground ,fg-dim))
        (ivory-themes--face 'corfu-default `(:background ,bg-alt :foreground ,fg))
        (ivory-themes--face 'corfu-current selected)
        (ivory-themes--face 'corfu-bar `(:background ,fg-faint))
        (ivory-themes--face 'corfu-border `(:background ,border))
        (ivory-themes--face 'corfu-annotations `(:foreground ,fg-dim))
        (ivory-themes--face 'company-tooltip `(:background ,bg-alt :foreground ,fg))
        (ivory-themes--face 'company-tooltip-selection selected)
        (ivory-themes--face 'company-tooltip-common match)
        (ivory-themes--face 'company-tooltip-common-selection match)
        (ivory-themes--face 'company-tooltip-annotation `(:foreground ,fg-dim))
        (ivory-themes--face 'company-tooltip-annotation-selection `(:background ,bg-active :foreground ,fg-alt))
        (ivory-themes--face 'company-scrollbar-bg `(:background ,bg-dim))
        (ivory-themes--face 'company-scrollbar-fg `(:background ,fg-faint))
        (ivory-themes--face 'company-preview `(:background ,bg-active :foreground ,fg))
        (ivory-themes--face 'company-preview-common match)
        (ivory-themes--face 'ivy-current-match selected)
        (ivory-themes--face 'ivy-minibuffer-match-face-1 match)
        (ivory-themes--face 'ivy-minibuffer-match-face-2 match)
        (ivory-themes--face 'ivy-minibuffer-match-face-3 match)
        (ivory-themes--face 'ivy-minibuffer-match-face-4 match)
        (ivory-themes--face 'ivy-posframe `(:background ,bg-alt :foreground ,fg))
        (ivory-themes--face 'ivy-posframe-border `(:background ,border))
        (ivory-themes--face 'swiper-match-face-1 match)
        (ivory-themes--face 'swiper-match-face-2 match)
        (ivory-themes--face 'swiper-match-face-3 match)
        (ivory-themes--face 'swiper-match-face-4 match)
        (ivory-themes--face 'helm-selection selected)
        (ivory-themes--face 'helm-match match)
        (ivory-themes--face 'helm-source-header `(:background ,bg-dim :foreground ,fg :weight bold))
        (ivory-themes--face 'which-key-key-face `(:foreground ,fg :weight bold))
        (ivory-themes--face 'which-key-command-description-face `(:foreground ,fg))
        (ivory-themes--face 'which-key-group-description-face `(:foreground ,fg-alt :weight bold))
        (ivory-themes--face 'which-key-local-map-description-face `(:foreground ,fg-dim))
        (ivory-themes--face 'embark-keybinding `(:foreground ,fg :weight bold))
        (ivory-themes--face 'transient-heading `(:foreground ,fg :weight bold))
        (ivory-themes--face 'transient-argument `(:foreground ,fg-alt :weight bold))
        (ivory-themes--face 'transient-inactive-argument `(:foreground ,fg-dim :weight normal))
        (ivory-themes--face 'transient-inapt-argument `(:foreground ,fg-faint :weight bold))
        (ivory-themes--face 'transient-value `(:foreground ,fg-alt :weight bold))
        (ivory-themes--face 'transient-inactive-value `(:foreground ,fg-dim :weight normal))
        (ivory-themes--face 'transient-unreachable `(:foreground ,fg-faint))
        (ivory-themes--face 'transient-inapt-suffix `(:foreground ,fg-faint :slant normal))
        (ivory-themes--face 'transient-active-infix `(:background ,bg-active :foreground ,fg :weight bold))
        (ivory-themes--face 'transient-enabled-suffix `(:foreground ,fg :weight bold))
        (ivory-themes--face 'transient-disabled-suffix `(:foreground ,fg-dim :weight normal))
        (ivory-themes--face 'transient-higher-level `(:underline t :weight bold))
        (ivory-themes--face 'transient-delimiter `(:foreground ,fg-dim))
        (ivory-themes--face 'transient-key `(:foreground ,fg :weight bold))
        (ivory-themes--face 'transient-key-stay `(:foreground ,fg :weight bold))
        (ivory-themes--face 'transient-key-noop `(:foreground ,fg-dim :weight bold))
        (ivory-themes--face 'transient-key-return `(:foreground ,fg-alt :weight bold))
        (ivory-themes--face 'transient-key-recurse `(:foreground ,fg-alt :weight bold))
        (ivory-themes--face 'transient-key-stack `(:foreground ,fg-alt :weight bold))
        (ivory-themes--face 'transient-key-exit `(:foreground ,fg :weight bold))
        (ivory-themes--face 'transient-unreachable-key `(:foreground ,fg-faint :weight bold))
        (ivory-themes--face 'transient-nonstandard-key `(:foreground ,fg-alt :underline t :weight bold))
        (ivory-themes--face 'transient-mismatched-key `(:foreground ,red :underline t :weight bold)))
       (mapcar (lambda (face) (ivory-themes--face face match))
               '(anzu-match-1 anzu-match-2 anzu-match-3 anzu-mode-line
                 avy-lead-face avy-lead-face-0 avy-lead-face-1 avy-lead-face-2))))))

(defun ivory-themes--faces-org-markdown (palette)
  "Return Org and Markdown faces for PALETTE."
  (ivory-themes--with-colors palette
    (let ((bold (if ivory-themes-bold-constructs 'bold 'normal))
          (slant (if ivory-themes-italic-constructs 'italic 'normal)))
      (list
       (ivory-themes--face 'org-document-title `(:foreground ,fg :weight bold :height 1.35))
       (ivory-themes--face 'org-document-info `(:foreground ,fg-alt))
       (ivory-themes--face 'org-document-info-keyword `(:foreground ,fg-dim))
       (ivory-themes--face 'org-level-1 `(:inherit outline-1))
       (ivory-themes--face 'org-level-2 `(:inherit outline-2))
       (ivory-themes--face 'org-level-3 `(:inherit outline-3))
       (ivory-themes--face 'org-level-4 `(:inherit outline-4))
       (ivory-themes--face 'org-level-5 `(:inherit outline-5))
       (ivory-themes--face 'org-level-6 `(:inherit outline-6))
       (ivory-themes--face 'org-level-7 `(:inherit outline-7))
       (ivory-themes--face 'org-level-8 `(:inherit outline-8))
       (ivory-themes--face 'org-block `(:background ,bg-block :extend t))
       (ivory-themes--face 'org-block-begin-line `(:background ,bg-dim :foreground ,fg-dim :extend t))
       (ivory-themes--face 'org-block-end-line `(:inherit org-block-begin-line))
       (ivory-themes--face 'org-code `(:inherit fixed-pitch :background ,bg-block :foreground ,fg-alt))
       (ivory-themes--face 'org-verbatim `(:inherit fixed-pitch :background ,bg-block :foreground ,fg-alt))
       (ivory-themes--face 'org-quote `(:background ,bg-block :foreground ,fg-alt :extend t))
       (ivory-themes--face 'org-verse `(:inherit org-quote))
       (ivory-themes--face 'org-table `(:foreground ,fg-alt))
       (ivory-themes--face 'org-formula `(:foreground ,fg :weight ,bold))
       (ivory-themes--face 'org-meta-line `(:foreground ,fg-dim))
       (ivory-themes--face 'org-drawer `(:foreground ,fg-dim))
       (ivory-themes--face 'org-property-value `(:foreground ,fg-alt))
       (ivory-themes--face 'org-special-keyword `(:foreground ,fg-dim :weight ,bold))
       (ivory-themes--face 'org-tag `(:foreground ,fg-dim :weight normal))
       (ivory-themes--face 'org-date `(:foreground ,fg :underline t))
       (ivory-themes--face 'org-footnote `(:foreground ,fg :underline t))
       (ivory-themes--face 'org-link `(:inherit link))
       (ivory-themes--face 'org-todo `(:foreground ,red :weight bold))
       (ivory-themes--face 'org-done `(:foreground ,green :weight bold))
       (ivory-themes--face 'org-headline-done `(:foreground ,fg-dim :strike-through t))
       (ivory-themes--face 'org-checkbox `(:foreground ,fg :weight bold))
       (ivory-themes--face 'org-priority `(:foreground ,fg :weight bold))
       (ivory-themes--face 'org-list-dt `(:foreground ,fg :weight ,bold))
       (ivory-themes--face 'org-hide `(:foreground ,bg))
       (ivory-themes--face 'org-agenda-date `(:foreground ,fg :weight bold))
       (ivory-themes--face 'org-agenda-date-today `(:foreground ,fg :weight bold :underline t))
       (ivory-themes--face 'org-agenda-date-weekend `(:foreground ,fg-dim :weight bold))
       (ivory-themes--face 'org-agenda-structure `(:foreground ,fg :weight bold))
       (ivory-themes--face 'org-agenda-done `(:foreground ,fg-dim :strike-through t))
       (ivory-themes--face 'org-agenda-clocking `(:background ,bg-active :foreground ,fg))
       (ivory-themes--face 'org-scheduled `(:foreground ,fg-alt))
       (ivory-themes--face 'org-scheduled-previously `(:foreground ,yellow :weight bold))
       (ivory-themes--face 'org-scheduled-today `(:foreground ,fg :weight bold))
       (ivory-themes--face 'org-upcoming-deadline `(:foreground ,yellow :weight bold))
       (ivory-themes--face 'org-warning `(:inherit warning))
       (ivory-themes--face 'org-modern-label `(:background ,bg-active :foreground ,fg :weight bold))
       (ivory-themes--face 'org-modern-date-active `(:foreground ,fg :underline t))
       (ivory-themes--face 'org-modern-date-inactive `(:foreground ,fg-dim :underline t))
       (ivory-themes--face 'org-modern-todo `(:inherit org-todo))
       (ivory-themes--face 'org-modern-done `(:inherit org-done))
       (ivory-themes--face 'markdown-header-face `(:foreground ,fg :weight bold))
       (ivory-themes--face 'markdown-header-face-1 `(:inherit markdown-header-face :height 1.30))
       (ivory-themes--face 'markdown-header-face-2 `(:inherit markdown-header-face :height 1.20))
       (ivory-themes--face 'markdown-header-face-3 `(:inherit markdown-header-face :height 1.12))
       (ivory-themes--face 'markdown-header-face-4 `(:inherit markdown-header-face :height 1.06))
       (ivory-themes--face 'markdown-header-face-5 `(:inherit markdown-header-face))
       (ivory-themes--face 'markdown-header-face-6 `(:inherit markdown-header-face :foreground ,fg-alt))
       (ivory-themes--face 'markdown-markup-face `(:foreground ,fg-dim))
       (ivory-themes--face 'markdown-metadata-key-face `(:foreground ,fg-dim :weight ,bold))
       (ivory-themes--face 'markdown-metadata-value-face `(:foreground ,fg-alt))
       (ivory-themes--face 'markdown-list-face `(:foreground ,fg :weight ,bold))
       (ivory-themes--face 'markdown-link-face `(:inherit link))
       (ivory-themes--face 'markdown-url-face `(:foreground ,fg-dim :underline t))
       (ivory-themes--face 'markdown-reference-face `(:foreground ,fg-alt))
       (ivory-themes--face 'markdown-blockquote-face `(:background ,bg-block :foreground ,fg-alt :extend t))
       (ivory-themes--face 'markdown-code-face `(:inherit fixed-pitch :background ,bg-block :extend t))
       (ivory-themes--face 'markdown-inline-code-face `(:inherit fixed-pitch :background ,bg-block :foreground ,fg-alt))
       (ivory-themes--face 'markdown-pre-face `(:inherit markdown-code-face))
       (ivory-themes--face 'markdown-language-keyword-face `(:foreground ,fg-dim :weight ,bold))
       (ivory-themes--face 'markdown-bold-face `(:weight bold))
       (ivory-themes--face 'markdown-italic-face `(:slant ,slant))
       (ivory-themes--face 'markdown-strike-through-face `(:strike-through t :foreground ,fg-dim))
       (ivory-themes--face 'markdown-gfm-checkbox-face `(:foreground ,fg :weight bold))
       (ivory-themes--face 'md-ts-delimiter `(:inherit markdown-markup-face))
       (ivory-themes--face 'md-ts-heading-1 `(:inherit markdown-header-face-1))
       (ivory-themes--face 'md-ts-heading-2 `(:inherit markdown-header-face-2))
       (ivory-themes--face 'md-ts-heading-3 `(:inherit markdown-header-face-3))
       (ivory-themes--face 'md-ts-heading-4 `(:inherit markdown-header-face-4))
       (ivory-themes--face 'md-ts-heading-5 `(:inherit markdown-header-face-5))
       (ivory-themes--face 'md-ts-heading-6 `(:inherit markdown-header-face-6))
       (ivory-themes--face 'md-ts-block-quote `(:inherit markdown-blockquote-face))
       (ivory-themes--face 'md-ts-code `(:inherit markdown-code-face))
       (ivory-themes--face 'md-ts-inline-code `(:inherit markdown-inline-code-face))
       (ivory-themes--face 'md-ts-language-keyword `(:inherit markdown-language-keyword-face))
       (ivory-themes--face 'md-ts-list-marker `(:inherit markdown-list-face))
       (ivory-themes--face 'md-ts-task-list-marker `(:inherit markdown-gfm-checkbox-face))
       (ivory-themes--face 'md-ts-strikethrough `(:inherit markdown-strike-through-face))))))

(defun ivory-themes--faces-vcs (palette)
  "Return VCS, diff, Magit, and review faces for PALETTE."
  (ivory-themes--with-colors palette
    (list
     (ivory-themes--face 'diff-added `(:background ,bg-added-faint :foreground ,fg-added :extend t))
     (ivory-themes--face 'diff-changed `(:background ,bg-changed-faint :foreground ,fg-changed :extend t))
     (ivory-themes--face 'diff-removed `(:background ,bg-removed-faint :foreground ,fg-removed :extend t))
     (ivory-themes--face 'diff-context `(:foreground ,fg-dim))
     (ivory-themes--face 'diff-file-header `(:background ,bg-active :foreground ,fg :weight bold :extend t))
     (ivory-themes--face 'diff-header `(:background ,bg-dim :foreground ,fg :weight bold :extend t))
     (ivory-themes--face 'diff-hunk-header `(:background ,bg-active :foreground ,fg :weight bold :extend t))
     (ivory-themes--face 'diff-index `(:inherit diff-file-header))
     (ivory-themes--face 'diff-indicator-added `(:foreground ,fg-added :weight bold))
     (ivory-themes--face 'diff-indicator-changed `(:foreground ,fg-changed :weight bold))
     (ivory-themes--face 'diff-indicator-removed `(:foreground ,fg-removed :weight bold))
     (ivory-themes--face 'diff-refine-added `(:background ,bg-added :foreground ,fg-added-intense))
     (ivory-themes--face 'diff-refine-changed `(:background ,bg-changed :foreground ,fg-changed-intense))
     (ivory-themes--face 'diff-refine-removed `(:background ,bg-removed :foreground ,fg-removed-intense))
     (ivory-themes--face 'ediff-current-diff-A `(:inherit diff-removed))
     (ivory-themes--face 'ediff-current-diff-B `(:inherit diff-added))
     (ivory-themes--face 'ediff-current-diff-C `(:inherit diff-changed))
     (ivory-themes--face 'ediff-even-diff-A `(:background ,bg-dim))
     (ivory-themes--face 'ediff-even-diff-B `(:background ,bg-dim))
     (ivory-themes--face 'ediff-even-diff-C `(:background ,bg-dim))
     (ivory-themes--face 'ediff-fine-diff-A `(:inherit diff-refine-removed))
     (ivory-themes--face 'ediff-fine-diff-B `(:inherit diff-refine-added))
     (ivory-themes--face 'ediff-fine-diff-C `(:inherit diff-refine-changed))
     (ivory-themes--face 'ediff-odd-diff-A `(:background ,bg-alt))
     (ivory-themes--face 'ediff-odd-diff-B `(:background ,bg-alt))
     (ivory-themes--face 'ediff-odd-diff-C `(:background ,bg-alt))
     (ivory-themes--face 'smerge-base `(:inherit diff-changed))
     (ivory-themes--face 'smerge-lower `(:inherit diff-added))
     (ivory-themes--face 'smerge-upper `(:inherit diff-removed))
     (ivory-themes--face 'smerge-markers `(:background ,bg-active :foreground ,fg :weight bold :extend t))
     (ivory-themes--face 'smerge-refined-added `(:inherit diff-refine-added))
     (ivory-themes--face 'smerge-refined-removed `(:inherit diff-refine-removed))
     (ivory-themes--face 'vc-annotate-face-0046FF `(:foreground ,fg-dim))
     (ivory-themes--face 'vc-annotate-face-00FF00 `(:foreground ,fg-alt))
     (ivory-themes--face 'vc-annotate-face-FF3C3C `(:foreground ,fg))
     (ivory-themes--face 'vc-annotate-face-FFFF00 `(:foreground ,fg-alt))
     (ivory-themes--face 'vc-annotate-background `(:background ,bg))
     (ivory-themes--face 'vc-annotate-background-mode `(:background ,bg))
     (ivory-themes--face 'vc-annotate-separator `(:foreground ,border))
     (ivory-themes--face 'git-gutter:added `(:foreground ,fg-added :background ,fg-added))
     (ivory-themes--face 'git-gutter:deleted `(:foreground ,fg-removed :background ,fg-removed))
     (ivory-themes--face 'git-gutter:modified `(:foreground ,fg-changed :background ,fg-changed))
     (ivory-themes--face 'git-gutter-fr:added `(:foreground ,fg-added))
     (ivory-themes--face 'git-gutter-fr:deleted `(:foreground ,fg-removed))
     (ivory-themes--face 'git-gutter-fr:modified `(:foreground ,fg-changed))
     (ivory-themes--face 'diff-hl-insert `(:foreground ,fg-added :background ,fg-added))
     (ivory-themes--face 'diff-hl-delete `(:foreground ,fg-removed :background ,fg-removed))
     (ivory-themes--face 'diff-hl-change `(:foreground ,fg-changed :background ,fg-changed))
     (ivory-themes--face 'magit-section-heading `(:foreground ,fg :weight bold :extend t))
     (ivory-themes--face 'magit-section-highlight `(:background ,bg-subtle :extend t))
     (ivory-themes--face 'magit-dimmed `(:foreground ,fg-dim))
     (ivory-themes--face 'magit-hash `(:foreground ,fg-faint))
     (ivory-themes--face 'magit-tag `(:background ,bg-active :foreground ,fg :weight bold :box (:line-width -1 :color ,border)))
     (ivory-themes--face 'magit-branch-current `(:background ,bg-active :foreground ,fg :weight bold :box (:line-width -1 :color ,border)))
     (ivory-themes--face 'magit-branch-local `(:foreground ,fg :weight bold))
     (ivory-themes--face 'magit-branch-remote `(:foreground ,fg-alt :weight bold))
     (ivory-themes--face 'magit-branch-remote-head `(:inherit magit-branch-remote :box (:line-width -1 :color ,border)))
     (ivory-themes--face 'magit-branch-upstream `(:foreground ,fg-dim :slant normal))
     (ivory-themes--face 'magit-branch-warning `(:inherit warning))
     (ivory-themes--face 'magit-head `(:foreground ,fg :weight bold :box (:line-width -1 :color ,border)))
     (ivory-themes--face 'magit-refname `(:foreground ,fg-dim))
     (ivory-themes--face 'magit-refname-pullreq `(:foreground ,fg-dim))
     (ivory-themes--face 'magit-refname-stash `(:foreground ,fg-dim))
     (ivory-themes--face 'magit-refname-wip `(:foreground ,fg-dim))
     (ivory-themes--face 'magit-keyword `(:foreground ,fg-alt :weight bold))
     (ivory-themes--face 'magit-keyword-squash `(:foreground ,yellow :weight bold))
     (ivory-themes--face 'magit-header-line `(:background ,bg-modeline :foreground ,fg :weight bold :box (:line-width 3 :color ,bg-modeline)))
     (ivory-themes--face 'magit-log-author `(:foreground ,fg-alt :weight normal :slant normal))
     (ivory-themes--face 'magit-log-date `(:foreground ,fg-dim :weight normal :slant normal))
     (ivory-themes--face 'magit-log-graph `(:foreground ,fg-dim))
     (ivory-themes--face 'magit-header-line-log-select `(:inherit magit-header-line))
     (ivory-themes--face 'magit-cherry-equivalent `(:foreground ,fg-dim))
     (ivory-themes--face 'magit-cherry-unmatched `(:foreground ,fg :weight bold))
     (ivory-themes--face 'magit-diff-added `(:background ,bg-added-faint :foreground ,fg-added :extend t))
     (ivory-themes--face 'magit-diff-added-highlight `(:background ,bg-added :foreground ,fg-added-intense :extend t))
     (ivory-themes--face 'magit-diff-base `(:background ,bg-changed-faint :foreground ,fg-changed :extend t))
     (ivory-themes--face 'magit-diff-base-highlight `(:background ,bg-changed :foreground ,fg-changed-intense :extend t))
     (ivory-themes--face 'magit-diff-context `(:foreground ,fg-dim :extend t))
     (ivory-themes--face 'magit-diff-context-highlight `(:background ,bg-dim :foreground ,fg-alt :extend t))
     (ivory-themes--face 'magit-diff-file-heading `(:foreground ,fg :weight bold :extend t))
     (ivory-themes--face 'magit-diff-file-heading-highlight `(:background ,bg-subtle :foreground ,fg :weight bold :extend t))
     (ivory-themes--face 'magit-diff-file-heading-selection `(:background ,bg-active :foreground ,fg :weight bold :extend t))
     (ivory-themes--face 'magit-diff-hunk-heading `(:background ,bg-active :foreground ,fg :weight bold :extend t))
     (ivory-themes--face 'magit-diff-hunk-heading-highlight `(:background ,bg-region :foreground ,fg :weight bold :extend t))
     (ivory-themes--face 'magit-diff-hunk-heading-selection `(:background ,bg-search :foreground ,fg :weight bold :extend t))
     (ivory-themes--face 'magit-diff-lines-heading `(:background ,bg-search :foreground ,fg :weight bold :extend t))
     (ivory-themes--face 'magit-diff-removed `(:background ,bg-removed-faint :foreground ,fg-removed :extend t))
     (ivory-themes--face 'magit-diff-removed-highlight `(:background ,bg-removed :foreground ,fg-removed-intense :extend t))
     (ivory-themes--face 'magit-diff-whitespace-warning `(:background ,fg-removed :foreground ,bg :weight bold))
     (ivory-themes--face 'magit-diffstat-added `(:foreground ,fg-added :weight bold))
     (ivory-themes--face 'magit-diffstat-removed `(:foreground ,fg-removed :weight bold))
     (ivory-themes--face 'magit-process-ng `(:foreground ,red :weight bold))
     (ivory-themes--face 'magit-process-ok `(:foreground ,green :weight bold))
     (ivory-themes--face 'magit-signature-bad `(:foreground ,red :weight bold))
     (ivory-themes--face 'magit-signature-error `(:foreground ,red :weight bold))
     (ivory-themes--face 'magit-signature-expired `(:foreground ,yellow :weight bold))
     (ivory-themes--face 'magit-signature-good `(:foreground ,green :weight bold))
     (ivory-themes--face 'magit-signature-revoked `(:foreground ,red :weight bold))
     (ivory-themes--face 'magit-signature-untrusted `(:foreground ,fg-dim :weight bold))
     (ivory-themes--face 'magit-blame-heading `(:background ,bg-active :foreground ,fg :extend t))
     (ivory-themes--face 'magit-blame-hash `(:foreground ,fg-alt))
     (ivory-themes--face 'magit-blame-name `(:foreground ,fg))
     (ivory-themes--face 'magit-blame-date `(:foreground ,fg-dim))
     (ivory-themes--face 'forge-topic-open `(:foreground ,fg :weight bold))
     (ivory-themes--face 'forge-topic-closed `(:foreground ,fg-dim :strike-through t))
     (ivory-themes--face 'forge-pullreq-open `(:inherit forge-topic-open))
     (ivory-themes--face 'forge-pullreq-merged `(:foreground ,green :weight bold))
     (ivory-themes--face 'forge-pullreq-rejected `(:foreground ,red :strike-through t))
     (ivory-themes--face 'code-review-comment-author-face `(:foreground ,fg :weight bold))
     (ivory-themes--face 'code-review-comment-body-face `(:foreground ,fg-alt))
     (ivory-themes--face 'code-review-comment-file-face `(:foreground ,fg-dim))
     (ivory-themes--face 'blamer-face `(:foreground ,fg-faint)))))

(defun ivory-themes--faces-diagnostics (palette)
  "Return diagnostic, compilation, xref, and LSP faces for PALETTE."
  (ivory-themes--with-colors palette
    (list
     (ivory-themes--face 'flymake-error `(:underline (:style line :color ,red)))
     (ivory-themes--face 'flymake-warning `(:underline (:style line :color ,yellow)))
     (ivory-themes--face 'flymake-note `(:underline (:style line :color ,green)))
     (ivory-themes--face 'flycheck-error `(:underline (:style line :color ,red)))
     (ivory-themes--face 'flycheck-warning `(:underline (:style line :color ,yellow)))
     (ivory-themes--face 'flycheck-info `(:underline (:style line :color ,green)))
     (ivory-themes--face 'flycheck-fringe-error `(:foreground ,red :weight bold))
     (ivory-themes--face 'flycheck-fringe-warning `(:foreground ,yellow :weight bold))
     (ivory-themes--face 'flycheck-fringe-info `(:foreground ,green :weight bold))
     (ivory-themes--face 'flycheck-posframe-background-face `(:background ,bg-alt))
     (ivory-themes--face 'flycheck-posframe-border-face `(:background ,border))
     (ivory-themes--face 'flycheck-posframe-face `(:background ,bg-alt :foreground ,fg))
     (ivory-themes--face 'compilation-column-number `(:foreground ,fg-dim))
     (ivory-themes--face 'compilation-error `(:foreground ,red :weight bold))
     (ivory-themes--face 'compilation-info `(:foreground ,green :weight bold))
     (ivory-themes--face 'compilation-line-number `(:foreground ,fg :weight bold))
     (ivory-themes--face 'compilation-mode-line-exit `(:foreground ,green :weight bold))
     (ivory-themes--face 'compilation-mode-line-fail `(:foreground ,red :weight bold))
     (ivory-themes--face 'compilation-mode-line-run `(:foreground ,yellow :weight bold))
     (ivory-themes--face 'compilation-warning `(:foreground ,yellow :weight bold))
     (ivory-themes--face 'xref-file-header `(:foreground ,fg :weight bold))
     (ivory-themes--face 'xref-line-number `(:foreground ,fg-dim))
     (ivory-themes--face 'xref-match `(:inherit match))
     (ivory-themes--face 'eglot-diagnostic-tag-deprecated-face `(:strike-through t))
     (ivory-themes--face 'eglot-diagnostic-tag-unnecessary-face `(:foreground ,fg-dim))
     (ivory-themes--face 'eglot-highlight-symbol-face `(:background ,bg-active))
     (ivory-themes--face 'eglot-mode-line `(:foreground ,fg :weight bold))
     (ivory-themes--face 'lsp-face-highlight-read `(:background ,bg-active))
     (ivory-themes--face 'lsp-face-highlight-textual `(:background ,bg-active))
     (ivory-themes--face 'lsp-face-highlight-write `(:background ,bg-active :weight bold))
     (ivory-themes--face 'lsp-face-semhl-constant `(:inherit font-lock-constant-face))
     (ivory-themes--face 'lsp-face-semhl-function `(:inherit font-lock-function-name-face))
     (ivory-themes--face 'lsp-face-semhl-keyword `(:inherit font-lock-keyword-face))
     (ivory-themes--face 'lsp-face-semhl-method `(:inherit font-lock-function-name-face))
     (ivory-themes--face 'lsp-face-semhl-operator `(:inherit font-lock-operator-face))
     (ivory-themes--face 'lsp-face-semhl-property `(:inherit font-lock-property-name-face))
     (ivory-themes--face 'lsp-face-semhl-string `(:inherit font-lock-string-face))
     (ivory-themes--face 'lsp-face-semhl-type `(:inherit font-lock-type-face))
     (ivory-themes--face 'lsp-headerline-breadcrumb-path-face `(:foreground ,fg-dim))
     (ivory-themes--face 'lsp-headerline-breadcrumb-separator-face `(:foreground ,fg-faint))
     (ivory-themes--face 'lsp-headerline-breadcrumb-symbols-face `(:foreground ,fg :weight bold))
     (ivory-themes--face 'lsp-ui-doc-background `(:background ,bg-alt))
     (ivory-themes--face 'lsp-ui-doc-header `(:background ,bg-active :foreground ,fg :weight bold))
     (ivory-themes--face 'lsp-ui-peek-header `(:background ,bg-active :foreground ,fg :weight bold))
     (ivory-themes--face 'lsp-ui-peek-list `(:background ,bg-alt :foreground ,fg))
     (ivory-themes--face 'lsp-ui-peek-peek `(:background ,bg :foreground ,fg))
     (ivory-themes--face 'lsp-ui-peek-selection `(:background ,bg-region :foreground ,fg :weight bold))
     (ivory-themes--face 'lsp-ui-sideline-code-action `(:foreground ,fg :weight bold))
     (ivory-themes--face 'eldoc-box-body `(:background ,bg-alt :foreground ,fg))
     (ivory-themes--face 'eldoc-box-border `(:background ,border))
     (ivory-themes--face 'sideline-default `(:foreground ,fg-dim))
     (ivory-themes--face 'sideline-symbol `(:foreground ,fg :weight bold)))))

(defun ivory-themes--faces-files-buffers (palette)
  "Return file manager, project tree, buffer, and terminal faces for PALETTE."
  (ivory-themes--with-colors palette
    (let ((bold (if ivory-themes-bold-constructs 'bold 'normal)))
      (list
       (ivory-themes--face 'dired-directory `(:foreground ,fg :weight bold))
       (ivory-themes--face 'dired-flagged `(:foreground ,red :weight bold))
       (ivory-themes--face 'dired-header `(:foreground ,fg :weight bold))
       (ivory-themes--face 'dired-ignored `(:foreground ,fg-faint))
       (ivory-themes--face 'dired-mark `(:foreground ,fg :weight bold))
       (ivory-themes--face 'dired-marked `(:background ,bg-active :foreground ,fg :weight bold))
       (ivory-themes--face 'dired-perm-write `(:foreground ,fg-alt))
       (ivory-themes--face 'dired-symlink `(:foreground ,fg-alt :weight ,bold))
       (ivory-themes--face 'dired-warning `(:inherit warning))
       (ivory-themes--face 'diredfl-dir-name `(:inherit dired-directory))
       (ivory-themes--face 'diredfl-file-name `(:foreground ,fg))
       (ivory-themes--face 'diredfl-file-suffix `(:foreground ,fg-dim))
       (ivory-themes--face 'diredfl-link-priv `(:foreground ,fg-alt))
       (ivory-themes--face 'diredfl-no-priv `(:foreground ,fg-faint))
       (ivory-themes--face 'diredfl-number `(:foreground ,fg-dim))
       (ivory-themes--face 'diredfl-read-priv `(:foreground ,fg-alt))
       (ivory-themes--face 'diredfl-symlink `(:inherit dired-symlink))
       (ivory-themes--face 'dirvish-hl-line `(:inherit hl-line))
       (ivory-themes--face 'dirvish-file-time `(:foreground ,fg-dim))
       (ivory-themes--face 'dirvish-file-size `(:foreground ,fg-dim))
       (ivory-themes--face 'dirvish-subtree-state `(:foreground ,fg-dim))
       (ivory-themes--face 'treemacs-directory-face `(:foreground ,fg :weight ,bold))
       (ivory-themes--face 'treemacs-file-face `(:foreground ,fg-alt))
       (ivory-themes--face 'treemacs-git-added-face `(:foreground ,fg-added :weight bold))
       (ivory-themes--face 'treemacs-git-conflict-face `(:foreground ,fg-removed :weight bold))
       (ivory-themes--face 'treemacs-git-ignored-face `(:foreground ,fg-faint))
       (ivory-themes--face 'treemacs-git-modified-face `(:foreground ,fg-changed :weight bold))
       (ivory-themes--face 'treemacs-git-renamed-face `(:foreground ,fg-added :weight bold))
       (ivory-themes--face 'treemacs-git-untracked-face `(:foreground ,fg-added :weight bold))
       (ivory-themes--face 'treemacs-root-face `(:foreground ,fg :weight bold))
       (ivory-themes--face 'neo-dir-link-face `(:inherit treemacs-directory-face))
       (ivory-themes--face 'neo-file-link-face `(:inherit treemacs-file-face))
       (ivory-themes--face 'neo-root-dir-face `(:inherit treemacs-root-face))
       (ivory-themes--face 'neo-vc-added-face `(:inherit treemacs-git-added-face))
       (ivory-themes--face 'neo-vc-conflict-face `(:inherit treemacs-git-conflict-face))
       (ivory-themes--face 'neo-vc-edited-face `(:inherit treemacs-git-modified-face))
       (ivory-themes--face 'neo-vc-ignored-face `(:inherit treemacs-git-ignored-face))
       (ivory-themes--face 'neo-vc-untracked-face `(:inherit treemacs-git-untracked-face))
       (ivory-themes--face 'ibuffer-title-face `(:foreground ,fg :weight bold))
       (ivory-themes--face 'ibuffer-marked-face `(:background ,bg-active :foreground ,fg :weight bold))
       (ivory-themes--face 'ibuffer-deletion-face `(:foreground ,red :strike-through t))
       (ivory-themes--face 'ibuffer-filter-group-name-face `(:foreground ,fg :weight bold))
       (ivory-themes--face 'eshell-prompt `(:foreground ,fg :weight bold))
       (ivory-themes--face 'eshell-ls-directory `(:foreground ,fg :weight bold))
       (ivory-themes--face 'eshell-ls-symlink `(:foreground ,fg-alt :weight bold))
       (ivory-themes--face 'eshell-ls-executable `(:foreground ,fg :weight bold))
       (ivory-themes--face 'eshell-ls-readonly `(:foreground ,fg-dim))
       (ivory-themes--face 'eshell-ls-unreadable `(:foreground ,fg-faint))
       (ivory-themes--face 'vterm-color-black `(:background ,bg :foreground ,fg-faint))
       (ivory-themes--face 'vterm-color-red `(:background ,red :foreground ,red))
       (ivory-themes--face 'vterm-color-green `(:background ,green :foreground ,green))
       (ivory-themes--face 'vterm-color-yellow `(:background ,yellow :foreground ,yellow))
       (ivory-themes--face 'vterm-color-blue `(:background ,fg-dim :foreground ,fg-dim))
       (ivory-themes--face 'vterm-color-magenta `(:background ,fg-alt :foreground ,fg-alt))
       (ivory-themes--face 'vterm-color-cyan `(:background ,fg-alt :foreground ,fg-alt))
       (ivory-themes--face 'vterm-color-white `(:background ,fg :foreground ,fg))
       (ivory-themes--face 'ansi-color-black `(:background ,bg :foreground ,fg-faint))
       (ivory-themes--face 'ansi-color-red `(:background ,red :foreground ,red))
       (ivory-themes--face 'ansi-color-green `(:background ,green :foreground ,green))
       (ivory-themes--face 'ansi-color-yellow `(:background ,yellow :foreground ,yellow))
       (ivory-themes--face 'ansi-color-blue `(:background ,fg-dim :foreground ,fg-dim))
       (ivory-themes--face 'ansi-color-magenta `(:background ,fg-alt :foreground ,fg-alt))
       (ivory-themes--face 'ansi-color-cyan `(:background ,fg-alt :foreground ,fg-alt))
       (ivory-themes--face 'ansi-color-white `(:background ,fg :foreground ,fg))))))

(defun ivory-themes--faces-modelines-extra (palette)
  "Return faces for modeline packages and auxiliary UI packages."
  (ivory-themes--with-colors palette
    (list
     (ivory-themes--face 'doom-modeline-bar `(:background ,modeline-accent :foreground ,bg))
     (ivory-themes--face 'doom-modeline-bar-inactive `(:background ,fg-faint :foreground ,bg))
     (ivory-themes--face 'doom-modeline-buffer-file `(:foreground ,fg :weight bold))
     (ivory-themes--face 'doom-modeline-buffer-modified `(:foreground ,fg :weight bold))
     (ivory-themes--face 'doom-modeline-info `(:foreground ,fg :weight bold))
     (ivory-themes--face 'doom-modeline-warning `(:foreground ,yellow :weight bold))
     (ivory-themes--face 'doom-modeline-urgent `(:foreground ,red :weight bold))
     (ivory-themes--face 'doom-modeline-project-dir `(:foreground ,fg-dim))
     (ivory-themes--face 'doom-modeline-project-parent-dir `(:foreground ,fg-faint))
     (ivory-themes--face 'doom-modeline-evil-normal-state `(:foreground ,fg :weight bold))
     (ivory-themes--face 'doom-modeline-evil-insert-state `(:foreground ,green :weight bold))
     (ivory-themes--face 'doom-modeline-evil-visual-state `(:foreground ,yellow :weight bold))
     (ivory-themes--face 'doom-modeline-evil-emacs-state `(:foreground ,fg-alt :weight bold))
     (ivory-themes--face 'mood-line-status-info `(:foreground ,fg :weight bold))
     (ivory-themes--face 'mood-line-status-neutral `(:foreground ,fg-dim))
     (ivory-themes--face 'mood-line-status-success `(:foreground ,green :weight bold))
     (ivory-themes--face 'mood-line-status-warning `(:foreground ,yellow :weight bold))
     (ivory-themes--face 'mood-line-status-error `(:foreground ,red :weight bold))
     (ivory-themes--face 'telephone-line-accent-active `(:background ,bg-active :foreground ,fg))
     (ivory-themes--face 'telephone-line-accent-inactive `(:background ,bg-modeline-inactive :foreground ,fg-inactive))
     (ivory-themes--face 'telephone-line-projectile `(:foreground ,fg :weight bold))
     (ivory-themes--face 'solaire-default-face `(:background ,bg-alt :foreground ,fg))
     (ivory-themes--face 'solaire-mode-line-face `(:inherit mode-line :background ,bg-modeline))
     (ivory-themes--face 'solaire-mode-line-inactive-face `(:inherit mode-line-inactive :background ,bg-modeline-inactive)))))

(defun ivory-themes--faces-misc (palette)
  "Return additional package faces for PALETTE."
  (ivory-themes--with-colors palette
    (let ((bold (if ivory-themes-bold-constructs 'bold 'normal)))
      (append
       (list
        (ivory-themes--face 'rainbow-delimiters-base-face `(:foreground ,fg-alt))
        (ivory-themes--face 'rainbow-delimiters-unmatched-face `(:foreground ,red :weight bold))
        (ivory-themes--face 'rainbow-delimiters-mismatched-face `(:foreground ,red :weight bold))
        (ivory-themes--face 'highlight-defined-function-name-face `(:inherit font-lock-function-name-face))
        (ivory-themes--face 'highlight-defined-variable-name-face `(:inherit font-lock-variable-name-face))
        (ivory-themes--face 'highlight-quoted-symbol `(:foreground ,fg-alt))
        (ivory-themes--face 'highlight-quoted-quote `(:foreground ,fg-dim))
        (ivory-themes--face 'macrostep-expansion-highlight-face `(:background ,bg-active))
        (ivory-themes--face 'paredit-mode-line-face `(:foreground ,fg-dim))
        (ivory-themes--face 'smartparens-strict-mode-face `(:foreground ,fg-dim))
        (ivory-themes--face 'sp-show-pair-match-face `(:inherit show-paren-match))
        (ivory-themes--face 'sp-show-pair-mismatch-face `(:inherit show-paren-mismatch))
        (ivory-themes--face 'hl-todo `(:foreground ,fg :background ,bg-active :weight bold))
        (ivory-themes--face 'jinx-misspelled `(:underline (:style line :color ,red)))
        (ivory-themes--face 'writegood-duplicates-face `(:underline (:style line :color ,yellow)))
        (ivory-themes--face 'writegood-passive-voice-face `(:underline (:style line :color ,yellow)))
        (ivory-themes--face 'writegood-weasels-face `(:underline (:style line :color ,yellow)))
        (ivory-themes--face 'pulse-highlight-start-face `(:background ,bg-active))
        (ivory-themes--face 'pulse-highlight-face `(:background ,bg-active))
        (ivory-themes--face 'beacon-fallback-background `(:background ,bg-search))
        (ivory-themes--face 'symbol-overlay-default-face `(:background ,bg-active))
        (ivory-themes--face 'symbol-overlay-face-1 `(:background ,bg-active))
        (ivory-themes--face 'symbol-overlay-face-2 `(:background ,bg-search))
        (ivory-themes--face 'symbol-overlay-face-3 `(:background ,bg-hl))
        (ivory-themes--face 'symbol-overlay-face-4 `(:background ,bg-region))
        (ivory-themes--face 'symbol-overlay-face-5 `(:background ,bg-removed-faint))
        (ivory-themes--face 'symbol-overlay-face-6 `(:background ,bg-changed-faint))
        (ivory-themes--face 'symbol-overlay-face-7 `(:background ,bg-added-faint))
        (ivory-themes--face 'symbol-overlay-face-8 `(:background ,bg-block))
        (ivory-themes--face 'breadcrumb-project-base-face `(:foreground ,fg-dim))
        (ivory-themes--face 'breadcrumb-project-crumbs-face `(:foreground ,fg-alt))
        (ivory-themes--face 'breadcrumb-project-leaf-face `(:foreground ,fg :weight bold))
        (ivory-themes--face 'breadcrumb-imenu-base-face `(:foreground ,fg-dim))
        (ivory-themes--face 'breadcrumb-imenu-crumbs-face `(:foreground ,fg-alt))
        (ivory-themes--face 'breadcrumb-imenu-leaf-face `(:foreground ,fg :weight bold))
        (ivory-themes--face 'help-key-binding `(:background ,bg-block :foreground ,fg :weight bold :box (:line-width -1 :color ,border)))
        (ivory-themes--face 'help-argument-name `(:foreground ,fg-alt :weight ,bold))
        (ivory-themes--face 'custom-button `(:background ,bg-active :foreground ,fg :box (:line-width -1 :color ,border)))
        (ivory-themes--face 'custom-button-mouse `(:background ,bg-region :foreground ,fg :box (:line-width -1 :color ,border)))
        (ivory-themes--face 'custom-button-pressed `(:background ,bg-search :foreground ,fg :box (:line-width -1 :color ,border)))
        (ivory-themes--face 'custom-button-unraised `(:foreground ,fg :underline t))
        (ivory-themes--face 'custom-changed `(:foreground ,yellow :weight bold))
        (ivory-themes--face 'custom-comment `(:background ,bg-block :foreground ,fg-alt))
        (ivory-themes--face 'custom-comment-tag `(:foreground ,fg-dim))
        (ivory-themes--face 'custom-documentation `(:foreground ,fg-alt))
        (ivory-themes--face 'custom-face-tag `(:foreground ,fg :weight bold :height 1.1))
        (ivory-themes--face 'custom-group-tag `(:foreground ,fg :weight bold :height 1.2))
        (ivory-themes--face 'custom-group-tag-1 `(:foreground ,fg :weight bold :height 1.1))
        (ivory-themes--face 'custom-invalid `(:foreground ,red :weight bold))
        (ivory-themes--face 'custom-link `(:inherit link))
        (ivory-themes--face 'custom-modified `(:foreground ,yellow :weight bold))
        (ivory-themes--face 'custom-rogue `(:foreground ,red :weight bold))
        (ivory-themes--face 'custom-saved `(:foreground ,green :weight bold))
        (ivory-themes--face 'custom-set `(:foreground ,fg :weight bold))
        (ivory-themes--face 'custom-state `(:foreground ,green :weight bold))
        (ivory-themes--face 'custom-themed `(:foreground ,fg :weight bold))
        (ivory-themes--face 'custom-variable-button `(:foreground ,fg :weight bold :underline t))
        (ivory-themes--face 'custom-variable-obsolete `(:foreground ,fg-dim :strike-through t))
        (ivory-themes--face 'custom-variable-tag `(:foreground ,fg :weight bold :height 1.1))
        (ivory-themes--face 'custom-visibility `(:inherit link)))
       (mapcar (lambda (face)
                 (ivory-themes--face face `(:foreground ,fg-alt :weight ,bold)))
               '(rainbow-delimiters-depth-1-face
                 rainbow-delimiters-depth-2-face
                 rainbow-delimiters-depth-3-face
                 rainbow-delimiters-depth-4-face
                 rainbow-delimiters-depth-5-face
                 rainbow-delimiters-depth-6-face
                 rainbow-delimiters-depth-7-face
                 rainbow-delimiters-depth-8-face
                 rainbow-delimiters-depth-9-face))))))

(defun ivory-themes--all-faces (palette)
  "Return all face specs for PALETTE."
  (append
   (ivory-themes--faces-basic palette)
   (ivory-themes--faces-font-lock palette)
   (ivory-themes--faces-outline palette)
   (ivory-themes--faces-completion palette)
   (ivory-themes--faces-org-markdown palette)
   (ivory-themes--faces-vcs palette)
   (ivory-themes--faces-diagnostics palette)
   (ivory-themes--faces-files-buffers palette)
   (ivory-themes--faces-modelines-extra palette)
   (ivory-themes--faces-misc palette)))

(defun ivory-themes--variables (palette)
  "Return theme variable specs for PALETTE."
  (ivory-themes--with-colors palette
    `((ansi-color-names-vector
       [,bg ,red ,green ,yellow ,fg-dim ,fg-alt ,fg-alt ,fg])
      (fci-rule-color ,border)
      (pdf-view-midnight-colors (,fg . ,bg)))))

;;;###autoload
(defun ivory-themes-load (theme)
  "Load Ivory THEME after disabling other enabled themes."
  (interactive
   (list (intern (completing-read "Load Ivory theme: " '(ivory-light ivory-dark)
                                  nil t nil nil "ivory-light"))))
  (mapc #'disable-theme custom-enabled-themes)
  (load-theme theme t))

;;;###autoload
(defun ivory-themes-toggle ()
  "Toggle between `ivory-light' and `ivory-dark'."
  (interactive)
  (ivory-themes-load
   (if (memq 'ivory-light custom-enabled-themes)
       'ivory-dark
     'ivory-light)))

;;;###autoload
(defun ivory-themes-apply (theme variant)
  "Apply THEME using the palette for VARIANT."
  (let ((palette (ivory-themes--palette variant)))
    (apply #'custom-theme-set-faces theme (ivory-themes--all-faces palette))
    (apply #'custom-theme-set-variables theme (ivory-themes--variables palette))))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide 'ivory-themes)

;;; ivory-themes.el ends here
